### ISSUE TITLE
Use temporary working directory

### ISSUE THREAD

**Issue by mweinelt** [lemoer/pynet#6]
The CI fails like this right now:

```
+ python3 ./tests/test_gluon_neighbour_info.py
Saving key "./ssh/id_rsa.key" failed: No such file or directory
Generating public/private rsa key pair.
Task exception was never retrieved
future: <Task finished coro=<gen_qemu_call() done, defined at /usr/local/lib/python3.7/dist-packages/pynet/__init__.py:170> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pynet/__init__.py", line 172, in gen_qemu_call
    shutil.copyfile('./' + image, './images/%02x.img' % node.id)
  File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './images/01.img'
Task exception was never retrieved
future: <Task finished coro=<gen_qemu_call() done, defined at /usr/local/lib/python3.7/dist-packages/pynet/__init__.py:170> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pynet/__init__.py", line 172, in gen_qemu_call
    shutil.copyfile('./' + image, './images/%02x.img' % node.id)
  File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './images/02.img'
```

This is because it is missing the ./images directory. It will also miss ./ptys and ./ssh. I'm thinking that the library should take care of creating these folders if they don't exist. It's unreasonable to expect people to guess which folders are required, and since we don't clone the Git repo anymore we don't have those folders precreated for us.

In fact I think the best way forward is to create a temporary working directory and dump everything in there.

**Comment by lemoer** [comment]
Implemented as optional feature via `--use-tmp-workdir` cli flag in 83e5db2.

**Comment by mweinelt** [comment]
Getting closer, but we're still missing `./logs` now.

```
+ python3 ./tests/test_gluon_neighbour_info.py --use-tmp-workdir
Generating public/private rsa key pair.
Your identification has been saved in /tmp/gluon-qemu-testlab/ssh/id_rsa.key.
Your public key has been saved in /tmp/gluon-qemu-testlab/ssh/id_rsa.key.pub.
The key fingerprint is:
SHA256:1lADuXAn94WCRXP6JG4m3wBRoRO5QJqealCOejldGpE gluon@da2d32ccdc62
The key's randomart image is:
+---[RSA 2048]----+
|     .. +OO...   |
|     +o *=+=. .  |
|  . E  +=*oo..   |
| + . o  o* +.    |
|o . + . S * .    |
|.. + + . = o     |
|. * o     . .    |
| o .             |
|                 |
+----[SHA256]-----+
Task exception was never retrieved
future: <Task finished coro=<read_to_buffer() done, defined at /usr/local/lib/python3.7/dist-packages/pynet/__init__.py:362> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pynet/__init__.py", line 369, in read_to_buffer
    with open('logs/' + node.hostname + '.log', 'wb') as f1:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/node1.log'
Task exception was never retrieved
future: <Task finished coro=<read_to_buffer() done, defined at /usr/local/lib/python3.7/dist-packages/pynet/__init__.py:362> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pynet/__init__.py", line 369, in read_to_buffer
    with open('logs/' + node.hostname + '.log', 'wb') as f1:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/node2.log'
```

**Comment by lemoer** [comment]
I pushed a fixup, please try again.

**Comment by mweinelt** [comment]
Yep, that fixes it. Check your query on IRC now!
